/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Filters = IDL.Record({
  'blur' : IDL.Bool,
  'sepia' : IDL.Bool,
  'blackAndWhite' : IDL.Bool,
  'invert' : IDL.Bool,
  'grayscale' : IDL.Bool,
});
export const Preference = IDL.Record({
  'filters' : Filters,
  'defaultResolution' : IDL.Tuple(IDL.Nat, IDL.Nat),
});

export const idlService = IDL.Service({
  'getAllPreferences' : IDL.Func([], [IDL.Vec(Preference)], ['query']),
  'getDefaultPreferences' : IDL.Func([], [Preference], ['query']),
  'getUserPreference' : IDL.Func([], [Preference], ['query']),
  'setUserPreference' : IDL.Func([Preference], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Filters = IDL.Record({
    'blur' : IDL.Bool,
    'sepia' : IDL.Bool,
    'blackAndWhite' : IDL.Bool,
    'invert' : IDL.Bool,
    'grayscale' : IDL.Bool,
  });
  const Preference = IDL.Record({
    'filters' : Filters,
    'defaultResolution' : IDL.Tuple(IDL.Nat, IDL.Nat),
  });
  
  return IDL.Service({
    'getAllPreferences' : IDL.Func([], [IDL.Vec(Preference)], ['query']),
    'getDefaultPreferences' : IDL.Func([], [Preference], ['query']),
    'getUserPreference' : IDL.Func([], [Preference], ['query']),
    'setUserPreference' : IDL.Func([Preference], [], []),
  });
};

export const init = ({ IDL }) => { return []; };